name: CI - Functional Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set version
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Display version
        run: go version

      - name: Run web api on docker
        run: |
          docker-compose up -d app

      - name: UnitTest
        run: go test -v ./tests/...
