name: CI - Unit Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set version
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Display version
        run: go version

      - name: Setup dependencies
        run: go mod tidy

      - name: Build Web Api
        run: go build -v ./cmd/web_api

      - name: UnitTest
        run: go test -v ./cmd/...
