name: Build & Unit Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set version
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Display version
        run: go version

      - name: Build
        run: go build -v ./...

      - name: Setup dependencies
        run: go mod tidy

      - name: Test
        run: go test -v ./...
